# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'gittermobile' do
    pod 'MZFayeClient',:git => 'https://github.com/iThinker/MZFayeClient.git', :commit => 'af451d3'
end

